spring:
  profiles:
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        auto-ddl:
        dialect: org.hibernate.dialect.MariaDBDialect
        
spring.profiles.include: real-db